# # # # # # # # # # # #
#        OPSN         #
# # # # # # # # # # # #

# Site Identity
name: "Open Psychological Science Nigeria"
title: "Open Psychological Science Nigeria"
description: "A community dedicated to advancing transparent, reproducible, and open psychological research in Nigeria."

# URL Configuration
url: "" 
baseurl: "" #For Root Domain
permalink: /:year/:month/:day/:title.html

# Navigation (Restricted to 5 core sections)
nav:
  - name: "home"
    href: "/"
  - name: "about"
    href: "/about"
  - name: "resources"
    href: "/resources"
  - name: "blog"
    href: "/blog"
  - name: "events"
    href: "/events"

# Build Settings
markdown: kramdown
highlighter: rouge
sass:
  style: :compressed

# Layout Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts" # This handles the Blog entries
    values:
      layout: "post"

# Optional: If 'Events' or 'Resources' use unique layouts 
# you can add them to collections here.
